apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ item.name }}"
  namespace: "{{ dashboard_namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ storage_size }}"