{
 "title": "Kiali Windsock Live Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Live Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT \"latency\" FROM \"requests\" WHERE $timeFilter GROUP BY session, pod\n",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Live Latency Percentile per pod",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"latency\", 25) as percentile25,  percentile(\"latency\", 50) as percentile50, percentile(\"latency\", 75) as percentile75, percentile(\"latency\", 99) as percentile99 FROM \"requests\" WHERE $timeFilter GROUP BY session, pod",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Live Latency Percentile (Total)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"latency\", 25) as percentile_total_25,  percentile(\"latency\", 50) as percentile_total_50, percentile(\"latency\", 75) as percentile_total_75, percentile(\"latency\", 99) as percentile_total_99 FROM \"requests\" WHERE $timeFilter GROUP BY session",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Live Response Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT \"response_size\" FROM \"requests\" WHERE $timeFilter GROUP BY pod, session",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT count( \"response_code\") FROM \"requests\" WHERE $timeFilter GROUP BY session, pod",
     "select": [
      [
       { "params": [ "response_code" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}