{
 "title": "Kiali Performance Test History",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filters" }
  ]
 },
 "panels": [
  {
   "title": "General Session Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT min(\"latency\") as minimum, percentile(\"latency\", 25) as percentile_25,  percentile(\"latency\", 50) as percentile_50, percentile(\"latency\", 75) as percentile_75, percentile(\"latency\", 99) as percentile_99, max(\"latency\") as maximum FROM \"requests\" GROUP BY session, route",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Response Size",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT min(\"response_size\") as minimum, percentile(\"response_size\", 25) as percentile_25,  percentile(\"response_size\", 50) as percentile_50, percentile(\"response_size\", 75) as percentile_75, percentile(\"response_size\", 99) as percentile_99, max(\"response_size\") as maximum FROM \"requests\" GROUP BY session, route",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Requests Count",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requests",
       "query": "SELECT count( \"latency\") FROM \"requests\" GROUP BY session, route, response_code",
       "select": [
        [
         { "params": [ "response_code" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "Select distinct(body) from requests Where error != '' group by session, route, response_code",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}